# Generated by Django 4.1.4 on 2022-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DriverID', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=255)),
                ('RegistrationNumber', models.CharField(max_length=255)),
                ('isAC', models.BooleanField()),
                ('Condition', models.CharField(max_length=255)),
                ('Pictures', models.CharField(max_length=255)),
            ],
        ),
    ]
