# Generated by Django 4.1.5 on 2023-02-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='DriverID',
        ),
    ]
