# Generated by Django 4.1.5 on 2023-02-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_alter_car_f_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='F_ID',
            new_name='FirebaseID',
        ),
    ]
