# Generated by Django 4.1.1 on 2023-03-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_rename_f_id_car_firebaseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='FirebaseID',
            new_name='DriverID',
        ),
    ]
