# Generated by Django 4.1.1 on 2023-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_rename_firebaseid_car_driverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Pictures',
            field=models.CharField(max_length=4000),
        ),
    ]
