# Generated by Django 4.1.4 on 2022-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirebaseID', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('NID', models.CharField(max_length=255)),
                ('Photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirebaseID', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Photo', models.CharField(max_length=255)),
            ],
        ),
    ]
