# Generated by Django 4.1.5 on 2023-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_driver_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='F_ID',
            field=models.CharField(max_length=255),
        ),
    ]
