# Generated by Django 4.1.5 on 2023-02-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_driver_firebaseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='F_ID',
            new_name='FirebaseID',
        ),
    ]
