# Generated by Django 4.1.1 on 2023-05-18 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirebaseID', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('NID', models.CharField(max_length=255)),
                ('Photo', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirebaseID', models.CharField(max_length=255, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('role', models.CharField(default='RIDER', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
