# Generated by Django 4.1.1 on 2023-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('otp', models.IntegerField()),
                ('resend', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
