# Generated by Django 4.1.5 on 2023-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_rider_firebaseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='FirebaseID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
