# Generated by Django 4.1.1 on 2023-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_deviceverification_created_at_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceverification',
            name='otp',
            field=models.CharField(max_length=255),
        ),
    ]
