# Generated by Django 4.1.5 on 2023-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_driver_firebaseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='F_ID',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
