# Generated by Django 4.1.1 on 2023-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_deviceverification_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceverification',
            old_name='otp',
            new_name='token',
        ),
    ]
