# Generated by Django 4.1.5 on 2023-02-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_driver_f_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='FirebaseID',
        ),
    ]
