# Generated by Django 4.1.5 on 2023-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_remove_car_driverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='F_ID',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
